### ISSUE TITLE
Self-addressed lamps should be better-supported

### ISSUE THREAD

**Issue by marcobrianza** [Jon-Bright/dalifi#1]
hello, I'm trying to use the lib with a simplified sketch

the broadcast message works
dali->sendDapc(Dali::broadcast, true, 254)

what is the address format for shot address and groups?

https://github.com/Jon-Bright/dalifi/blob/0af19229c89edc85188e68d75797056a1594c5d3/library/dali.cpp#L435
realy confuses me

If I comment it, I can use the method sendDapc with the address as a byte in the DALI standard format.

thank you
Marco

**Comment by Jon-Bright** [comment]
You almost certainly want to use the `addrs = dali->reAddressLamps(&nLamps);` code as seen in the example.  This follows this procedure:

1. Begins address initialization
2. Broadcasts a message telling all lamps to randomize their addresses.  The lamps pick a random 24-bit address.
3. Use a binary search process to find the 24-bit address of a single lamp with no assigned short address (this is in `findDevice`).
4. If no lamp was found, finish. Otherwise, assign the next available short (6-bit) address to the lamp found.
5. Go to 3.

After this is done, all lamps will have a 6-bit short address assigned to them.  Depending on your lamps and application, you may want to do something more (if you always want a particular lamp to have a particular short address).

I've not played with groups at all, but in principle, once the lamps have short addresses, you can add them to groups. The address byte can address either individual short addresses or groups. For individual short addresses the top bit is `0`, the next 6 bits are the short address and the bottom bit is `0` for DAPC (Direct Arc Power Control - directly setting level) and `1` otherwise.  For groups, the top bit is `1`, the next two bits are `00`, the next four bits are the 16-bit group ID and the bottom bit is again DAPC.

HTH.

If you do stuff with groups or feel like some of this would have been helpful in the project docs somewhere, I'm happy to take pull requests, but for the time being, I'll close this issue.

**Comment by marcobrianza** [comment]
I have the feeling that  addr ^= 1 inverts the last bit (so it could turn it to 1) when we should have it fixed to 0

**Comment by Jon-Bright** [comment]
Ah, I see what you're saying.  This is in fact correct, if you've previously used `reAddressLamps`.  At https://github.com/Jon-Bright/dalifi/blob/0af19229c89edc85188e68d75797056a1594c5d3/library/dali.cpp#L517 you can see that the addresses are returned with the 1 bit already sent, so only sendDapc inverts the bit to zero.  I hadn't considered the case of people doing their own address assignment.  Is that what you're doing?  If so, I'll reopen the issue.

**Comment by marcobrianza** [comment]
Yes, I address lamps with a dedicated DALI tool, otherwise I may connect to a DALI bus with already addressed lamps.

**Comment by Jon-Bright** [comment]
OK, understood.  I should be able to do a fix for that this weekend.

**Comment by marcobrianza** [comment]
thank you, I will test is asp

**Comment by Jon-Bright** [comment]
https://github.com/Jon-Bright/dalifi/commit/30ad1835ea71426921f120f218fd47839ef958a7 should resolve this. I've tested it locally, although since I don't have a device to separately address the lamps, I can't check your case (but the change is simple, so I'm pretty sure it'll work). Please let me know!

**Comment by marcobrianza** [comment]
hi, thank you, I can test it on monday

**Comment by marcobrianza** [comment]
Hi, with the latest code I can send the light level to all kind of addresses.
I created a wrapper function to make it more friendly to use as addr as the number we call it

typedef enum {
  addrBroadcast = 0, 
  addrSingle,
  addrGroup
} addrMode_t;

bool sendLevel(addrMode_t addrMode, byte addr, byte level ) { 

  if (addrMode == addrBroadcast) { 
    if (addr==0) addr= B11111100; //broadcast unadressed
    else addr = B11111110;
  } else if (addrMode == addrSingle) { 
    addr = addr << 1;
  } else if (addrMode == addrGroup) { 
    addr = addr << 1;
    addr = addr | B10000000;
  }
  return(dali->sendDapc(addr, true, level));
}

**Comment by marcobrianza** [comment]
works for me
